### ISSUE TITLE
3D Keypoints

### ISSUE THREAD

**Issue by cnmckee13** [mgiant/MP-GCN#1]
Hello! Thank you for your repo- I was wondering if this could work with 3D keypoint annotations. What would need to be changed?

**Comment by mgiant** [comment]
Thank you for your interest in our repository, and sorry for the late reply. 

To answer your question: yes, our model is fully capable of working with 3D keypoint annotations. In fact, by default, the model's input is 3-dimensional <x,y,v> keypoints. If you're looking to work with 3D <x,y,z> keypoints, you won't need to make any changes to the default configuration.
